// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYoXSWLlqcBscWt7UV-vaiPr1ujyqDS6g',
    appId: '1:298543902249:web:c9e52dc5b6a20e9f05b638',
    messagingSenderId: '298543902249',
    projectId: 'gym-helper-89ba5',
    authDomain: 'gym-helper-89ba5.firebaseapp.com',
    storageBucket: 'gym-helper-89ba5.firebasestorage.app',
    measurementId: 'G-DJEPZF2T4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfK9fY912yu2EIAkfejXi-9rm0W-tX7r0',
    appId: '1:298543902249:android:b94c5726705e85ec05b638',
    messagingSenderId: '298543902249',
    projectId: 'gym-helper-89ba5',
    storageBucket: 'gym-helper-89ba5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPsM8sm72vZlblqESwPoG8AT4LvHrhikY',
    appId: '1:298543902249:ios:0186ef902820a35105b638',
    messagingSenderId: '298543902249',
    projectId: 'gym-helper-89ba5',
    storageBucket: 'gym-helper-89ba5.firebasestorage.app',
    iosBundleId: 'com.hasryl.gymHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPsM8sm72vZlblqESwPoG8AT4LvHrhikY',
    appId: '1:298543902249:ios:0186ef902820a35105b638',
    messagingSenderId: '298543902249',
    projectId: 'gym-helper-89ba5',
    storageBucket: 'gym-helper-89ba5.firebasestorage.app',
    iosBundleId: 'com.hasryl.gymHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYoXSWLlqcBscWt7UV-vaiPr1ujyqDS6g',
    appId: '1:298543902249:web:e8645693a0edabb905b638',
    messagingSenderId: '298543902249',
    projectId: 'gym-helper-89ba5',
    authDomain: 'gym-helper-89ba5.firebaseapp.com',
    storageBucket: 'gym-helper-89ba5.firebasestorage.app',
    measurementId: 'G-9ZVVB5DXXC',
  );
}
