// STUB: Firebase configuration
//
// This file must be generated by running:
//   flutterfire configure
//
// Prerequisites:
//   1. Install FlutterFire CLI:  dart pub global activate flutterfire_cli
//   2. Log in to Firebase:       firebase login
//   3. From project root run:    flutterfire configure
//
// The command above will overwrite this file with real API keys and
// project identifiers tied to your Firebase project.
//
// Until then, Firebase.initializeApp() will fail gracefully — the app
// will run in offline / unauthenticated mode.
